Invite.create(
  [
    { token: '5VBIx', tag: 'Señor Fabio Benjumea Vélez' },
    { token: 'aScgH', tag: 'Señora Luz Elena Giraldo de la Cuesta e Hija' },
    { token: 'AWFTJ', tag: 'Señor Jorge Sebastián Bolívar Cuartas, Señora e Hijo' },
    { token: 'nzlwQ', tag: 'Señor Simón Bolívar Montenegro y Señora' },
    { token: 'IQLEN', tag: 'Señor Francisco Luis Giraldo Gallego, Señora e Hijos' },
    { token: 'HDPto', tag: 'Señor Francisco Javier Toro Gallego, Señora  e Hijos' },
    { token: 'qUFRT', tag: 'Señora Victoria Eugenia Giraldo Cuesta e Hijos' },
    { token: 'Mjk2S', tag: 'Señor Eduardo Arturo Gil Trigos' },
    { token: 'eTfCG', tag: 'Señor Luis Fernando Giraldo Cuesta, Señora e Hijos' },
    { token: 'Zn6Vx', tag: 'Ricardo Benjumea Valderrama e Isabella Gaviria Correa' },
    { token: 'C1brq', tag: 'Felipe Benjumea Valderrama' },
    { token: 'i4r9h', tag: 'Señor Edgar de Jesús Arango Vélez, Señora e Hijos' },
    { token: 'ync4o', tag: 'Daniela Baena Moreno' },
    { token: 'xSilD', tag: 'Señora Aurora Duque de Arcila' },
    { token: '8FTPU', tag: 'Señor Jorge Humberto Arcila Duque e Hijos' },
    { token: 'IJkId', tag: 'Estefanía Vargas Yepes' },
    { token: 'cVQVV', tag: 'Señor Jaime Alfonso Blair Ospina, Señora e Hijos' },
    { token: '6RoUD', tag: 'Señor Javier Hernando Arcila Duque, Señora e Hijos' },
    { token: 'uJrm4', tag: 'Señor Carlos Mario Sierra Duque, Señora e Hijos' },
    { token: 'AJsDR', tag: 'Mateo Tabares García' },
    { token: 'G5a42', tag: 'Señora Olga Duque de Sierra' },
    { token: 'h6cOC', tag: 'Jaime Alberto Arcila Duque e Hija' },
    { token: 'QV3xC', tag: 'Señor Victor Hugo Jiménez Fernández, Señora e Hijos' },
    { token: 'IkWhM', tag: 'Señora Nelly Montoya Cadavid' },
    { token: 'qgLwQ', tag: 'Marta Elena Gallego García y Rocío Gallego García' },
    { token: '5jdWx', tag: 'Familia Duque Garcés' },
    { token: '9CeQY', tag: 'Señor Fabio León Echeverri Restrepo y Señora' },
    { token: '5ai10', tag: 'Señor Juan Mauricio Echeverry Restrepo, Señora e Hija' },
    { token: 'ho9sF', tag: 'Daniel Felipe Calad Agudelo y Monica Echeverry Arango' },
    { token: 'OSayh', tag: 'Álvaro Arango Vélez' },
    { token: 'zM5t4', tag: 'Diego Alejandro López Londoño' },
    { token: '1XxDW', tag: 'Juan Camilo Valencia Muñoz' },
    { token: 'KB0qx', tag: 'Señor Jonathan Villa Errón y Señora' },
    { token: 'TrWiv', tag: 'Claudia Maryeri Muñoz Trejos' },
    { token: 'jnXeI', tag: 'Marcia Dienny Montoya Vicente' },
    { token: 'H3KFo', tag: 'Carlos Andrés Galvis Villegas' },
    { token: 'RbpVF', tag: 'Juan David Gallego López y Alejandra Barrera Restrepo' },
    { token: 'kKPYX', tag: 'Señor Carlos Eduardo Campiño Correa y Señora' },
    { token: '1MNAJ', tag: 'Paola Andrea Téllez García' },
    { token: 'qwoL7', tag: 'Héctor Alejandro Patiño Pérez y Estefany Londoño Bedoya' },
    { token: 'mwey3', tag: 'Sandra Carolina Vélez Holguín' },
    { token: 'ipRwR', tag: 'Señor Alejandro Calderón Vélez y Señora' },
    { token: 'fkXPm', tag: 'Señor Juan Camilo Bohórquez Escalante y Señora' },
    { token: 'WrnLi', tag: 'Cristian David Múnera Puerta y Lina Marcela Morales Fernández' },
  ]
)

User.create(
  [
    { first_name: 'Jorge', second_name: 'Alejandro', first_last_name: 'Benjumea', second_last_name: 'Giraldo', email: 'j.alejandro.benjumea@gmail.com' },
    { first_name: 'Alejandra', first_last_name: 'Arango', second_last_name: 'Arcila', email: 'alejandra.arango89@gmail.com' },
    { invite_id: Invite.find_by_token('5VBIx').id, first_name: 'Fabio', first_last_name: 'Benjumea', second_last_name: 'Vélez', email: 'fabio.benjumea@gmail.com' },
    { invite_id: Invite.find_by_token('aScgH').id, first_name: 'Luz', second_name: 'Elena', first_last_name: 'Giraldo', second_last_name: 'De La Cuesta', email: 'elenagiraldodel@hotmail.com' },
    { invite_id: Invite.find_by_token('aScgH').id, first_name: 'Paula', second_name: 'Andrea', first_last_name: 'Benjumea', second_last_name: 'Giraldo', email: 'benjumea_paula@hotmail.com' },
    { invite_id: Invite.find_by_token('AWFTJ').id, first_name: 'Ana', second_name: 'María', first_last_name: 'Benjumea', second_last_name: 'Giraldo', email: 'abenjumeagiraldo@gmail.com' },
    { invite_id: Invite.find_by_token('AWFTJ').id, first_name: 'Jorge', second_name: 'Sebastián', first_last_name: 'Bolívar', second_last_name: 'Cuartas', email: 'sebastianbolivar@hotmail.com' },
    { invite_id: Invite.find_by_token('AWFTJ').id, first_name: 'Maximiliano', first_last_name: 'Bolívar', second_last_name: 'Benjumea' },
    { invite_id: Invite.find_by_token('nzlwQ').id, first_name: 'Alicia', first_last_name: 'Cuartas', second_last_name: 'Bustamante' },
    { invite_id: Invite.find_by_token('nzlwQ').id, first_name: 'Simón', first_last_name: 'Bolívar', second_last_name: 'Montenegro', email: 'simon.bolivar@une.net.co' },
    { invite_id: Invite.find_by_token('IQLEN').id, first_name: 'Luz', second_name: 'Elena', first_last_name: 'Cuesta', second_last_name: 'De Giraldo' },
    { invite_id: Invite.find_by_token('IQLEN').id, first_name: 'Francisco', first_last_name: 'Giraldo', second_last_name: 'Gallego' },
    { invite_id: Invite.find_by_token('IQLEN').id, first_name: 'Maria', second_name: 'Patricia', first_last_name: 'Giraldo', second_last_name: 'De La Cuesta' },
    { invite_id: Invite.find_by_token('IQLEN').id, first_name: 'Francisco', second_name: 'Javier', first_last_name: 'Giraldo', second_last_name: 'De La Cuesta' },
    { invite_id: Invite.find_by_token('HDPto').id, first_name: 'Clara', second_name: 'Ines', first_last_name: 'Giraldo', second_last_name: 'De La Cuesta' },
    { invite_id: Invite.find_by_token('HDPto').id, first_name: 'Francisco', first_last_name: 'Toro' },
    { invite_id: Invite.find_by_token('HDPto').id, first_name: 'Juan', second_name: 'Camilo', first_last_name: 'Toro', second_last_name: 'Giraldo' },
    { invite_id: Invite.find_by_token('HDPto').id, first_name: 'Santiago', first_last_name: 'Toro', second_last_name: 'Giraldo' },
    { invite_id: Invite.find_by_token('qUFRT').id, first_name: 'Victoria', second_name: 'Eugenia', first_last_name: 'Giraldo', second_last_name: 'De La Cuesta' },
    { invite_id: Invite.find_by_token('qUFRT').id, first_name: 'Sebastián', first_last_name: 'Diaz', second_last_name: 'Giraldo' },
    { invite_id: Invite.find_by_token('qUFRT').id, first_name: 'Daniel', first_last_name: 'Pineda', second_last_name: 'Giraldo' },
    { invite_id: Invite.find_by_token('Mjk2S').id, first_name: 'Eduardo', first_last_name: 'Gil' },
    { invite_id: Invite.find_by_token('eTfCG').id, first_name: 'Luis', second_name: 'Fernando', first_last_name: 'Giraldo', second_last_name: 'De La Cuesta' },
    { invite_id: Invite.find_by_token('eTfCG').id, first_name: 'Alexandra', first_last_name: 'Arango' },
    { invite_id: Invite.find_by_token('eTfCG').id, first_name: 'Pablo', first_last_name: 'Giraldo', second_last_name: 'Arango' },
    { invite_id: Invite.find_by_token('eTfCG').id, first_name: 'Esteban', first_last_name: 'Giraldo', second_last_name: 'Arango' },
    { invite_id: Invite.find_by_token('Zn6Vx').id, first_name: 'Ricardo', first_last_name: 'Benjumea', second_last_name: 'Valderrama', email: 'ricardobenjumeav@gmail.com' },
    { invite_id: Invite.find_by_token('Zn6Vx').id, first_name: 'Isabella', first_last_name: 'Gaviria', second_last_name: 'Correa', email: 'isabellagaviriac@gmail.com' },
    { invite_id: Invite.find_by_token('C1brq').id, first_name: 'Felipe', first_last_name: 'Benjumea', second_last_name: 'Valderrama', email: 'felipebenjumeav@gmail.com' },
    { invite_id: Invite.find_by_token('i4r9h').id, first_name: 'Edgar', second_name: 'De Jesús', first_last_name: 'Arango', second_last_name: 'Vélez', email: 'edgar_1270@yahoo.es' },
    { invite_id: Invite.find_by_token('i4r9h').id, first_name: 'Claudia', second_name: 'Elena', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'claudia.ardu@hotmail.com' },
    { invite_id: Invite.find_by_token('i4r9h').id, first_name: 'Ana', second_name: 'María', first_last_name: 'Arango', second_last_name: 'Arcila', email: 'anamaria.arangoarcila@gmail.com' },
    { invite_id: Invite.find_by_token('i4r9h').id, first_name: 'Felipe', first_last_name: 'Arango', second_last_name: 'Arcila', email: 'felipearangoarcila@gmail.com' },
    { invite_id: Invite.find_by_token('ync4o').id, first_name: 'Daniela', first_last_name: 'Baena', second_last_name: 'Moreno', email: 'dbm021096@gmail.com' },
    { invite_id: Invite.find_by_token('xSilD').id, first_name: 'Francisca', second_name: 'Aurora', first_last_name: 'Duque', second_last_name: 'Garcés' },
    { invite_id: Invite.find_by_token('8FTPU').id, first_name: 'Jorge', second_name: 'Humberto', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'jorge.arcila@cobelen.com' },
    { invite_id: Invite.find_by_token('8FTPU').id, first_name: 'Carolina', first_last_name: 'Arcila', second_last_name: 'Correa', email: 'carolina.arcila1@udea.edu.co' },
    { invite_id: Invite.find_by_token('8FTPU').id, first_name: 'Camilo', first_last_name: 'Arcila', second_last_name: 'Correa', email: 'cacdzya-1995@hotmail.com' },
    { invite_id: Invite.find_by_token('IJkId').id, first_name: 'Estefanía', first_last_name: 'Vargas', second_last_name: 'Yepes', email: 'estefaniavargasy@hotmail.com' },
    { invite_id: Invite.find_by_token('cVQVV').id, first_name: 'Gloria', second_name: 'Patricia', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'patricia-arcila@hotmail.es' },
    { invite_id: Invite.find_by_token('cVQVV').id, first_name: 'Jaime', second_name: 'Alfonso', first_last_name: 'Blair', second_last_name: 'Ospina', email: 'jaimeblairospina@hotmail.con' },
    { invite_id: Invite.find_by_token('cVQVV').id, first_name: 'Alejandro', first_last_name: 'Blair', second_last_name: 'Arcila', email: 'alejoblair1997@gmail.com' },
    { invite_id: Invite.find_by_token('cVQVV').id, first_name: 'Sebastián', first_last_name: 'Blair', second_last_name: 'Arcila', email: 'sebastianblaira1996@gmail.com' },
    { invite_id: Invite.find_by_token('6RoUD').id, first_name: 'Javier', second_name: 'Hernando', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'javiar2728@hotmail.com' },
    { invite_id: Invite.find_by_token('6RoUD').id, first_name: 'Nancy', first_last_name: 'Velásquez', second_last_name: 'Gallego' },
    { invite_id: Invite.find_by_token('6RoUD').id, first_name: 'Laura', first_last_name: 'Arcila', second_last_name: 'Velásquez', email: 'lauraarcilav28@gmail.com' },
    { invite_id: Invite.find_by_token('6RoUD').id, first_name: 'Andrés', first_last_name: 'Arcila', second_last_name: 'Velásquez' },
    { invite_id: Invite.find_by_token('uJrm4').id, first_name: 'Isabel', second_name: 'Cristina', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'iarcila@sura.com.co' },
    { invite_id: Invite.find_by_token('uJrm4').id, first_name: 'Carlos', second_name: 'Mario', first_last_name: 'Sierra', second_last_name: 'Duque', email: 'csierrad@hotmail.com' },
    { invite_id: Invite.find_by_token('uJrm4').id, first_name: 'Daniela', first_last_name: 'Sierra', second_last_name: 'Arcila', email: 'danisierra888@gmail.com' },
    { invite_id: Invite.find_by_token('AJsDR').id, first_name: 'Mateo', first_last_name: 'Tabares', second_last_name: 'Garcia', email: 'mrteo9712@hotmail' },
    { invite_id: Invite.find_by_token('G5a42').id, first_name: 'Olga', first_last_name: 'Duque', second_last_name: 'De Sierra' },
    { invite_id: Invite.find_by_token('h6cOC').id, first_name: 'Jaime', second_name: 'Alberto', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'jaimerdu@gmail.com' },
    { invite_id: Invite.find_by_token('h6cOC').id, first_name: 'María', second_name: 'Camila', first_last_name: 'Arcila', second_last_name: 'Saldarriaga'},
    { invite_id: Invite.find_by_token('QV3xC').id, first_name: 'Luz', second_name: 'María', first_last_name: 'Arcila', second_last_name: 'Duque', email: 'luzmariaarciladuque@gmail.com' },
    { invite_id: Invite.find_by_token('QV3xC').id, first_name: 'Victor', second_name: 'Hugo', first_last_name: 'Jimenez', second_last_name: 'Fernandez', email: 'victorjimenez1279@gmail.com' },
    { invite_id: Invite.find_by_token('QV3xC').id, first_name: 'Matias', first_last_name: 'Jimenez', second_last_name: 'Arcila' },
    { invite_id: Invite.find_by_token('QV3xC').id, first_name: 'Emiliana', first_last_name: 'Jimenez', second_last_name: 'Arcila' },
    { invite_id: Invite.find_by_token('IkWhM').id, first_name: 'Nelly', first_last_name: 'Montoya', second_last_name: 'Cadavid' },
    { invite_id: Invite.find_by_token('qgLwQ').id, first_name: 'Rocio', first_last_name: 'Gallego', second_last_name: 'Arcila', email: 'rocioga555@hotmail.com' },
    { invite_id: Invite.find_by_token('qgLwQ').id, first_name: 'Marta', second_name: 'Elena', first_last_name: 'Gallego', second_last_name: 'Arcila', email: 'martagallego.7@hotmail.com' },
    { invite_id: Invite.find_by_token('5jdWx').id, first_name: 'Luis', second_name: 'Guillermo', first_last_name: 'Duque', second_last_name: 'Garcés' },
    { invite_id: Invite.find_by_token('5jdWx').id, first_name: 'Gloria', second_name: 'Marina', first_last_name: 'Duque', second_last_name: 'Garcés' },
    { invite_id: Invite.find_by_token('9CeQY').id, first_name: 'María', second_name: 'Elena', first_last_name: 'Uribe', second_last_name: 'Arcila', email: 'meua65@hotmail.com' },
    { invite_id: Invite.find_by_token('9CeQY').id, first_name: 'Fabio', second_name: 'Leon', first_last_name: 'Echeverri', second_last_name: 'Restrepo', email: 'fabioecheverrisas@hotmail.com' },
    { invite_id: Invite.find_by_token('5ai10').id, first_name: 'Luz', second_name: 'Estela', first_last_name: 'Arango', second_last_name: 'Vélez' },
    { invite_id: Invite.find_by_token('5ai10').id, first_name: 'Juan', second_name: 'Mauricio', first_last_name: 'Echeverry', second_last_name: 'Restrepo', email: 'mauro.eche@yahoo.com' },
    { invite_id: Invite.find_by_token('5ai10').id, first_name: 'Veronica', first_last_name: 'Echeverry', second_last_name: 'Arango', email: 'veronica.echeverry@yahoo.com' },
    { invite_id: Invite.find_by_token('ho9sF').id, first_name: 'Daniel', second_name: 'Felipe', first_last_name: 'Calad', second_last_name: 'Agudelo', email: 'daniel_calad@hotmail.com' },
    { invite_id: Invite.find_by_token('ho9sF').id, first_name: 'Monica', first_last_name: 'Echeverry', second_last_name: 'Arango', email: 'monikita_0813@yahoo.com' },
    { invite_id: Invite.find_by_token('OSayh').id, first_name: 'Álvaro', first_last_name: 'Arango', second_last_name: 'Vélez', email: 'alarango99@gmail.com' },
    { invite_id: Invite.find_by_token('zM5t4').id, first_name: 'Diego', second_name: 'Alejandro', first_last_name: 'López', second_last_name: 'Londoño' },
    { invite_id: Invite.find_by_token('1XxDW').id, first_name: 'Juan', second_name: 'Camilo', first_last_name: 'Valencia', second_last_name: 'Muñoz', email: 'juancamilov09@gmail.com' },
    { invite_id: Invite.find_by_token('KB0qx').id, first_name: 'Laura', first_last_name: 'Pareja', second_last_name: 'Pérez', email: 'lpareja1@hotmail.com' },
    { invite_id: Invite.find_by_token('KB0qx').id, first_name: 'Jonathan', first_last_name: 'Villa', second_last_name: 'Errón', email: 'jonathanvillah@hotmail.com' },
    { invite_id: Invite.find_by_token('TrWiv').id, first_name: 'Claudia', second_name: 'Maryeri', first_last_name: 'Muñoz', second_last_name: 'Trejos', email: 'claudiamaryery@gmail.com' },
    { invite_id: Invite.find_by_token('jnXeI').id, first_name: 'Marcia', second_name: 'Dienny', first_last_name: 'Montoya', second_last_name: 'Vicente', email: 'marciadienny@gmail.com' },
    { invite_id: Invite.find_by_token('H3KFo').id, first_name: 'Carlos', second_name: 'Andrés', first_last_name: 'Galvis', second_last_name: 'Villegas', email: 'carlosagalvisv@gmail.com' },
    { invite_id: Invite.find_by_token('RbpVF').id, first_name: 'Juan', second_name: 'David', first_last_name: 'Gallego', second_last_name: 'Lopez', email: 'juandagallego@hotmail.com' },
    { invite_id: Invite.find_by_token('RbpVF').id, first_name: 'Alejandra', first_last_name: 'Barrera', second_last_name: 'Restrepo', email: 'alejabarrera88@gmail.com' },
    { invite_id: Invite.find_by_token('kKPYX').id, first_name: 'Carlos', second_name: 'Eduardo', first_last_name: 'Campiño', second_last_name: 'Correa', email: 'cecampino@gmail.com' },
    { invite_id: Invite.find_by_token('kKPYX').id, first_name: 'Luz', second_name: 'Adriana', first_last_name: 'Gutiérrez', second_last_name: 'Nieto', email: 'luzadrianaguti@gmail.com' },
    { invite_id: Invite.find_by_token('1MNAJ').id, first_name: 'Paola', second_name: 'Andrea', first_last_name: 'Téllez', second_last_name: 'Garcia', email: 'paolatellezg@gmail com' },
    { invite_id: Invite.find_by_token('qwoL7').id, first_name: 'Héctor', second_name: 'Alejandro', first_last_name: 'Patiño', second_last_name: 'Pérez' },
    { invite_id: Invite.find_by_token('qwoL7').id, first_name: 'Estefany', second_name: 'Londoño', first_last_name: 'Bedoya' },
    { invite_id: Invite.find_by_token('mwey3').id, first_name: 'Sandra', second_name: 'Carolina', first_last_name: 'Velez', second_last_name: 'Holguin', email: 'krolina35@hotmail.com' },
    { invite_id: Invite.find_by_token('ipRwR').id, first_name: 'Tatiana', second_name: 'Andrea', first_last_name: 'Echavarria', second_last_name: 'Henao', email: 'taechava@gmail.com' },
    { invite_id: Invite.find_by_token('ipRwR').id, first_name: 'Alejandro', first_last_name: 'Calderón', second_last_name: 'Velez', email: 'alejandrocalderonvelez@gmail.com' },
    { invite_id: Invite.find_by_token('fkXPm').id, first_name: 'Natalia', first_last_name: 'Salamanca', second_last_name: 'Hernandez', email: 'natalia.salamanca.h@gmail.com' },
    { invite_id: Invite.find_by_token('fkXPm').id, first_name: 'Juan', second_name: 'Camilo', first_last_name: 'Bohorquez', second_last_name: 'Escalante', email: 'jacma600@gmail.com' },
    { invite_id: Invite.find_by_token('WrnLi').id, first_name: 'Cristian', second_name: 'David', first_last_name: 'Múnera', second_last_name: 'Puerta', email: 'cmunerap@gmail.com' },
    { invite_id: Invite.find_by_token('WrnLi').id, first_name: 'Lina', second_name: 'Marcela', first_last_name: 'Morales', second_last_name: 'Fernández', email: 'lina.morales.f@hotmail.com'}
  ]
)
